package com.example.data.youtube

import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONObject
import java.io.IOException
import java.util.regex.Pattern

data class CaptionTrack(
    val baseUrl: String,
    val languageCode: String,
    val name: String,
    val isAutoGenerated: Boolean
)

data class YouTubeVideoInfo(
    val videoId: String,
    val title: String,
    val author: String,
    val thumbnailUrl: String,
    val captionTracks: List<CaptionTrack>
)

object YouTubeTranscriptExtractor {
    private val client = OkHttpClient.Builder()
        .connectTimeout(15, java.util.concurrent.TimeUnit.SECONDS)
        .readTimeout(15, java.util.concurrent.TimeUnit.SECONDS)
        .build()

    fun extractVideoId(url: String): String? {
        val cleaned = url.trim()
        val pattern = Pattern.compile(
            "(?:https?:\\/\\/)?(?:www\\.)?(?:youtube\\.com\\/(?:[^\\/\\n\\s]+\\/\\S+\\/|(?:v|e(?:mbed)?)\\/|\\S*?[?&]v=)|youtu\\.be\\/|youtube\\.com\\/shorts\\/)([a-zA-Z0-9_-]{11})",
            Pattern.CASE_INSENSITIVE
        )
        val matcher = pattern.matcher(cleaned)
        return if (matcher.find()) matcher.group(1) else null
    }

    suspend fun fetchVideoInfo(videoId: String): YouTubeVideoInfo? {
        val url = "https://www.youtube.com/watch?v=$videoId"
        val request = Request.Builder()
            .url(url)
            .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36")
            .header("Accept-Language", "ru,en;q=0.9")
            .build()

        return kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
            try {
                client.newCall(request).execute().use { response ->
                    if (!response.isSuccessful) return@withContext null
                    val html = response.body?.string() ?: return@withContext null
                    parseHtmlForVideoInfo(videoId, html)
                }
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }
    }

    private fun parseHtmlForVideoInfo(videoId: String, html: String): YouTubeVideoInfo? {
        val prefix = "ytInitialPlayerResponse = "
        val startIndex = html.indexOf(prefix)
        if (startIndex == -1) return null
        
        val jsonStart = startIndex + prefix.length
        var bracketCount = 0
        var endIndex = jsonStart
        for (i in jsonStart until html.length) {
            val c = html[i]
            if (c == '{') bracketCount++
            else if (c == '}') {
                bracketCount--
                if (bracketCount == 0) {
                    endIndex = i + 1
                    break
                }
            }
        }
        
        if (endIndex <= jsonStart) return null
        val jsonStr = html.substring(jsonStart, endIndex)
        
        return try {
            val responseJson = JSONObject(jsonStr)
            val videoDetails = responseJson.optJSONObject("videoDetails")
            val title = videoDetails?.optString("title", "YouTube Video") ?: "YouTube Video"
            val author = videoDetails?.optString("author", "Unknown Author") ?: "Unknown Author"
            val thumbnailUrl = "https://img.youtube.com/vi/$videoId/hqdefault.jpg"
            
            val captions = responseJson.optJSONObject("captions")
            val playerCaptionsTracklistRenderer = captions?.optJSONObject("playerCaptionsTracklistRenderer")
            val captionTracksJson = playerCaptionsTracklistRenderer?.optJSONArray("captionTracks")
            
            val list = mutableListOf<CaptionTrack>()
            if (captionTracksJson != null) {
                for (i in 0 until captionTracksJson.length()) {
                    val track = captionTracksJson.optJSONObject(i) ?: continue
                    val baseUrl = track.optString("baseUrl") ?: continue
                    val languageCode = track.optString("languageCode", "")
                    val nameObj = track.optJSONObject("name")
                    val name = nameObj?.optString("simpleText", languageCode) ?: languageCode
                    val vssId = track.optString("vssId", "")
                    val isAutoGenerated = vssId.startsWith("a.")
                    
                    list.add(CaptionTrack(baseUrl, languageCode, name, isAutoGenerated))
                }
            }
            
            YouTubeVideoInfo(videoId, title, author, thumbnailUrl, list)
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    suspend fun fetchTranscript(baseUrl: String): String? {
        val url = if (baseUrl.contains("fmt=json3")) baseUrl else "$baseUrl&fmt=json3"
        val request = Request.Builder()
            .url(url)
            .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36")
            .build()
            
        return kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
            try {
                client.newCall(request).execute().use { response ->
                    if (!response.isSuccessful) return@withContext null
                    response.body?.string()
                }
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }
    }
}
